import '../util/constants.dart';

import '../util/r.dart';

const supportedFiats = [
  'USD',
  'EUR',
  'GBP',
  'AUD',
  'CAD',
  'NZD',
  'ARS',
  'BRL',
  'CHF',
  'CLP',
  'COP',
  'CZK',
  'DKK',
  'HKD',
  'ILS',
  'INR',
  'ISK',
  'JPY',
  'KRW',
  'MXN',
  'MYR',
  'NOK',
  'PHP',
  'PLN',
  'SEK',
  'SGD',
  'THB',
  'VND',
  'ZAR',
];

const supportedFiatNames = [
  'United States dollar',
  'Euro',
  'British Pound Sterling',
  'Australian Dollar',
  'Canadian Dollar',
  'New Zealand Dollar',
  'Argentine Peso',
  'Brazilian Real',
  'Swiss Franc',
  'Chilean Peso',
  'Colombian peso',
  'Czech Koruna',
  'Danish Krona',
  'Hong Kong Dollar',
  'Israeli New Shekel',
  'Indian Rupee',
  'Icelandic Krona',
  'Japanese Yen',
  'South Korean Won',
  'Mexican Peso',
  'Malaysian Ringgit',
  'Norwegian Krone',
  'Norwegian Krone',
  'Polish Złoty',
  'Swedish Krona',
  'Singapore Dollar',
  'Thai Baht',
  'đồng Việt Nam ',
  'South African Rand',
];

const wyreDomain = 'api.sendwyre.com';
const wyreTestDomain = 'api.testwyre.com';

const supportedFiatsFlag = [
  R.resourcesIcFlagUsdPng,
  R.resourcesIcFlagEurPng,
  R.resourcesIcFlagGbpPng,
  R.resourcesIcFlagAudPng,
  R.resourcesIcFlagCadPng,
  R.resourcesIcFlagNzdPng,
  R.resourcesIcFlagArsPng,
  R.resourcesIcFlagBrlPng,
  R.resourcesIcFlagChfPng,
  R.resourcesIcFlagClpPng,
  R.resourcesIcFlagCopPng,
  R.resourcesIcFlagCzkPng,
  R.resourcesIcFlagDkkPng,
  R.resourcesIcFlagHkdPng,
  R.resourcesIcFlagIlsPng,
  R.resourcesIcFlagInrPng,
  R.resourcesIcFlagIskPng,
  R.resourcesIcFlagJpyPng,
  R.resourcesIcFlagKrwPng,
  R.resourcesIcFlagMxnPng,
  R.resourcesIcFlagMyrPng,
  R.resourcesIcFlagNokPng,
  R.resourcesIcFlagPhpPng,
  R.resourcesIcFlagPlnPng,
  R.resourcesIcFlagSekPng,
  R.resourcesIcFlagSgdPng,
  R.resourcesIcFlagThbPng,
  R.resourcesIcFlagVndPng,
  R.resourcesIcFlagZarPng,
];

const supportedContries = [
  'DZ',
  'AR',
  'AU',
  'AT',
  'BE',
  'BO',
  'BR',
  'CA',
  'CL',
  'CO',
  'CR',
  'CY',
  'CZ',
  'DK',
  'DO',
  'EE',
  'FI',
  'FR',
  'DE',
  'GR',
  'HK',
  'IS',
  'IN',
  'ID',
  'IE',
  'IL',
  'IT',
  'JP',
  'LV',
  'LT',
  'LU',
  'MY',
  'MX',
  'NP',
  'NL',
  'NZ',
  'NO',
  'PY',
  'PE',
  'PH',
  'PL',
  'PT',
  'SG',
  'SK',
  'SI',
  'ZA',
  'KR',
  'ES',
  'SE',
  'CH',
  'TZ',
  'TH',
  'TR',
  'GB',
  'US',
  'VN',
];

const supportedCryptos = ['USDT', 'USDC'];
const supportedCryptosId = [erc20USDT, erc20USDC];
